CREATE TABLE IF NOT EXISTS notes(
  id SERIAL PRIMARY KEY,
  folder_id INTEGER REFERENCES folders(id) ON DELETE CASCADE NOT NULL,
  name TEXT NOT NULL,
  content TEXT,
  modified TIMESTAMPTZ NOT NULL DEFAULT now()
);